---
title: Copertura
slug: /copertura
---
# Copertura
Copertura superiore trasparente monopezzo e sportello frontale per Flying Bear Ghost 4S/5

## Materiali

* [Foglio di Plexiglass (o policarbonato) da 2 mm (max 4 mm)](https://www.amazon.it/gp/product/B00HWRE5O6/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1)
* Taglierino ben affilato o altro utensile di taglio
* Silicone e/o colla a caldo
* Pistola termica
* Bulloneria
* Trapano
* Dremel (o trapano con punte adeguate)
* Barra di metalli di almeno 50 cm
* Sergenti da falegname
* Nastro isolante nero largo
* Magneti
* Opzionale: [Termometro circolare](https://www.amazon.it/Termometro-igrometro-misuratore-temperatura-incorporato/dp/B083BW81SZ/ref=sr_1_11?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=6TV0Z9SG89YV&dchild=1&keywords=termometro+circolare&qid=1605974380&sprefix=termometro+circ%2Caps%2C201&sr=8-11)


## Procedura Coperchio
Tagliare il foglio di plexiglass come mostrato in figura escludendo le aree tratteggiate. Le misure esatte (che tengono conto dei raccordi degli spigoli) sono riportate sotto alla figura

[![](/img/foglio.png)](/img/foglio.png)


[![](/img/Coperchio_superiore_FB_Ghost.jpg)](/img/Coperchio_superiore_FB_Ghost.jpg)

Le misure, a prodotto finito, dovrebbero essere 390x335x120 mm

Se si dovesse disporre di utensili da taglio che permettono di tagliare l’intera sezione di foglio, è possibile realizzare l’intera calotta senza giunture rendendola totalmente trasparente

Se invece ciò non fosse possibile, bisogna farlo con un taglierino incidendo parte della superficie e spezzando il foglio lungo l’incisione. Ciò obbliga a fare tagli dritti, quindi le due “ali” (L e R in figura) dovranno poi essere successivamente incollate

Non si dimentichi di tagliare anche la fessura per il passaggio dei cavi e del tubo in PTFE

Ottenuto il foglio tagliato delle giuste dimensioni, si disegnino le linee di piega (in giallo nell’immagine) aiutandosi con la barra di metallo o un righello

Per realizzare gli spigoli a 90°, posizionare la linea di piega in corrispondenza di uno spigolo vivo del piano di lavoro e bloccare il foglio con barra di metallo e sergenti agli estremi quanto più vicino possibile allo spigolo

Si scaldi la zona con pistola termica e quando il materiale arriva a temperatura di transizione vetrosa (di rammollimento) piegare, magari aiutandosi con una tavola di legno

Si prenda come riferimento [questo video](https://www.youtube.com/watch?v=78RNAA8-Dx8) oppure [questa alternativa](https://www.youtube.com/watch?v=r3L2Lz9K9rQ)

Per gli spigoli a 45° il procedimento è lo stesso, ma prima di farlo è necessario creare un supporto. Si potrebbe usare un foglio di compensato sottile sorretto da angolari stampati in PETG avvitati o incollati al piano di lavoro

[Supporto 45 gradi STL](https://cdn.discordapp.com/attachments/748683783053508608/782748854171861013/45.STL)

Ottenuto il foglio (o i fogli nel caso si siano tagliate le facce laterali L e R), giuntare gli spigoli con dei semplici angolari stampati (si consiglia di stamparli al 200% di dimensione e incollati con colla a caldo (o silicone)

[Angolare 2 STL](https://cdn.discordapp.com/attachments/748683783053508608/782748864020086844/ang2.STL)

[Angolare 3 STL](https://cdn.discordapp.com/attachments/748683783053508608/782748867144712192/ang3.STL)

Nel caso in cui i L e R siano separati, si suggerisce di stampare 2 ang3.stl per i due spigoli posteriori e 6 ang2.stl da distribuire lungo la giunzione. Altrimenti saranno sufficienti 4 ang2.stl da posizionare nei 4 spigoli di base

Una volta asciugato il collante, sigillare tutti gli spigoli con del silicone

**Nota estetica:**

Nel caso in cui L e R siano a sé stanti (come in foto) e quindi siano a vista le giunture, è possibile coprire il tutto con del nastro isolante largo nero (in foto è stato usato uno da 40 mm) per dare un senso di continuità estetica con la struttura sottostante

[![](/img/detail.jpg)](/img/detail.jpg)

Nel caso in cui si voglia inserire il termometro/igrometro, praticare un foro da 42 mm al centro della faccia inclinata

Per farlo usare una fresa a tazza adeguata oppure forare col trapano lungo la circonferenza e uniformare la superficie col dremel (o la punta di un saldatore)

[![](/img/detailFront.jpg)](/img/detailFront.jpg)

Bisogna ora realizzare col dremel (ma anche con un saldatore o un trapano) le sedi per i ganci da stampare

[Incastro STL](https://cdn.discordapp.com/attachments/748683783053508608/782748872438054952/incastro.STL)

Bisogna realizzare due semicerchi di diametro 10 mm la cui distanza dai centri è 20 mm. È bene distanziarsi un paio di cm dai bordi per permettere il corretto inserimento della linguetta tra telaio o pannello laterale

Dopo aver verificato il corretto inserimento del gancio sul plexiglass, porre un po’ di colla a caldo o silicone all’interno e inserire sul pannello

[![](/img/incastro.png)](/img/incastro.png)

[![](/img/incastrosotto.jpg)](/img/incastrosotto.jpg)

[![](/img/incastroirl.jpg)](/img/incastroirl.jpg)

Dopo aver stampato il [coperchio posteriore](https://cdn.discordapp.com/attachments/748683783053508608/782748869069897778/Cornice.STL), posizionarlo adeguatamente e fissarlo con colla a caldo o silicone. Si è scelto di stamparlo di colore trasparenti per ragioni estetiche, ma qualsiasi altro colore va bene

[![](/img/back.jpg)](/img/back.jpg)
 

## Procedura Sportello

artendo da un pannello 37x50cm (in celeste nell’immagine precedente), mantenendo 37 cm di larghezza, tagliare all’altezza desiderata. Si tenga però conto che, per posizionare i magneti per la chiusura, è necessario lasciare almeno 1 cm di sovrapposizione tra plexiglass e telaio metallico, come mostrato in figura

Smussare gli spigoli col dremel o una lima/carta vetrata impiegando come dima [questo pezzo](https://cdn.discordapp.com/attachments/748683783053508608/782748869997625344/dima_raccordo.STL)

Procurarsi 4 bulloni testa svasata M4 con relativi dadi. Per la lunghezza è bene scegliere i più corti disponibili senza però andare sotto i 10 mm

Discorso totalmente analogo ma con 5 bulloni M3

Procurarsi anche 2 bulloni testa svasata M3x50 (la lunghezza più variare nel range 30-55 mm) con relativi dadi

Dopo aver stampato [tutti i componenti](https://cdn.discordapp.com/attachments/748683783053508608/782750197213560862/Cerniere.zip), inserire il bullone M3 nella cerniera di sinistra (facendo coincidere la svasatura) e imbullonarlo così da ottenere un perno verticale sul quale inserire l’altra cerniera

[![](/img/cerniera.jpg)](/img/cerniera.jpg)

Successivamente posizionare i dadi M4 nell’apposita sede esagonale e posizionare il pezzo, dall’interno, in corrispondenza dei fori. Fissare la cerniera con i bulloni M4 senza però stringere così da poter poi registrare il tutto

[![](/img/inside.jpg)](/img/inside.jpg)

Posizionare la cerniera di sinistra e collocare in posizione il pannello così da poter segnare con un pennarello dove dover praticare i fori da 3 mm sul plexiglass. Realizzare un foro nella parte destra per il pomello

Realizzati i 4 fori, analogamente a quanto fatto per le altre cerniere, fissare le cerniere di destra con bulloni e dadi M3

Collocare l’intero pannello e, una volta essersi assicurati della corretta apertura e chiusura, stringere i bulloni

[![](/img/cerniera2.jpg)](/img/cerniera2.jpg)

Stampare il [pomello](https://cdn.discordapp.com/attachments/748683783053508608/782748875571331092/pomello.STL)

inserendo un dado M3 all’interno ([video di riferimento](https://www.youtube.com/watch?v=LwLt3kRHhX0)) e avvitarlo col relativo bullone

[![](/img/handle.jpg)](/img/handle.jpg)

Posizionare i magneti dove necessario e incollarli al plexiglass con colla a caldo (o attack, ma le esalazioni potrebbero rovinare le superfici come osservabile nelle foto)

[![](/img/magTop.jpg)](/img/magTop.jpg)

[![](/img/magBottom.jpg)](/img/magBottom.jpg)

:::info
E' possibile utilizzare 3 cerniere come nelle foto praticando un foro da 4mm accanto ad uno preesistente alla stessa distanza degli altri. Ovviamente bisogna procurarsi la relativa bulloneria
:::

[![](/img/sideCopertura.jpg)](/img/sideCopertura.jpg)
